blueprint:
  name: Light Timer
  description: Turn a light on and off based on Time
  domain: automation
  input:
    start_time:
      name: Turn on time
      selector:
        time:
    stop_time:
      name: Turn off time
      selector:
        time:
    target_light:
      name: Light
      selector:
        target:
          entity:
            domain: light

trigger:
  - platform: time
    at: !input start_time
    id: trigger_start
  - platform: time
    at: !input stop_time
    id: trigger_stop

action:
- choose:
  - conditions:
    - condition: trigger
      id: trigger_start
    sequence:
    - service: light.turn_on
      target: !input target_light
  - conditions:
    - condition: trigger
      id: trigger_stop
    sequence:
    - service: light.turn_off
      target: !input target_light
  default:
    - service: light.toggle
      target: !input target_light
